### PR TITLE
Add app links to front page

### PR DESCRIPTION
**Pull request by tinaroh**
screen shot 2018-09-18 at 6 33 36 pm

Kept the mailing list for now 

Not sure why it changed the .json page format...  Where can I download the formatter settings?

### CODE REVIEW

**Comment by osdiab** [comment]
I think the formatter should just work? But it's OK for now.

**Comment by osdiab** [comment]
We maybe ought to also just put the app links front and center on the splash page rather than having to click two buttons

But I don't feel strongly lol

**Comment by osdiab** [comment]
Separately we should give the option to join the mailing list when you sign up

**Comment by tinaroh** [comment]
oh sounds good!

**Pull request merged**
